### ISSUE TITLE
update model version on https://packagist.org/packages/myparcelnl/magento

### ISSUE THREAD

**Issue by bohdan-berezhniy** [myparcelnl/magento#204]
please update model version on https://packagist.org/packages/myparcelnl/magento

**Comment by RichardPerdaan** [comment]
Hi @bohdan-berezhniy,

The MyParcel version on packagist.org is updated to 2.4.0-beta.3.
The reason why he is marked unstable is because 2.4.0-beta.1 was a big adjustment and we are still testing a lot. However, we do want to give you the chance to use this version.

As soon as we find that the plugin is stable, this version will be updated to 2.4.0.
