### ISSUE TITLE
Can not combine magento 2 delivery options

### ISSUE THREAD

**Issue by koopjesboom** [myparcelnl/magento#288]
See mi illustration for the details.
If i use Default Magento free shipping options the options of the Myparcel extension will not be unchecked.

![Multiple cheched shipment options](https://user-images.githubusercontent.com/15247780/59603798-a6769300-910a-11e9-87d1-efdf8276d300.jpg)

**Comment by RichardPerdaan** [comment]
Hi @koopjesboom 

Thank you for passing on this issue. Unfortunately, this problem has already been noted as an issue (#228). Unfortunately I had no time to solve this problem, because of large projects where I am involved in. This problem is the number one for me to solve. I will start wit it when I am done with a major adjustment in the MyParcel SDK.

**Comment by koopjesboom** [comment]
Thank you for the answer. What is the estimated time frame you think it is resolved?
