### ISSUE TITLE
Problem with more than one shipping method in checkout.

### ISSUE THREAD

**Issue by onlinemusketeers** [myparcelnl/magento#319]
Version 3.0.3

The MyParcel shipping method is not deselected after choosing a different shipping method in the checkout.
Solution: Uncheck radio button if other shipping method is checked.
Thanks!

![image](https://user-images.githubusercontent.com/19552989/68581973-f23f2580-0479-11ea-8485-ce9da073d968.png)

**Comment by RichardPerdaan** [comment]
Hi @onlinemusketeers ,

From version `[3.0.4-beta.1](https://github.com/myparcelnl/magento/releases)` I have been working on this problem, so I would like to ask you to install at least this version.

If the problem still exists then I would like to hear from you.

For now I will close the issue, you can always open it again.

**Comment by onlinemusketeers** [comment]
Hi @RichardPerdaan ,

Thanks a lot Richard!  I have been testing it with: (latest Magento 2.3.3) 
- myparcelnl/magento - 3.0.4-beta.2 
- myparcelnl/sdk - v3.0.3     

Your update seems to work when I choosed "home delivery". But when choosing 'pick up at location' it's still possible to select both MyParcel and a different shipper.

Can you test it too to confirm this with me?

![image](https://user-images.githubusercontent.com/19552989/68618121-f2b2dd00-04c8-11ea-9325-fbd702c5f971.png)

**Comment by Calypso971** [comment]
Problem is still there in 3.1.0 - commented on it on the original issue #228 
3.0.4 was even a bit better, in 3.1.0 it's fully back.

To be honest, it's getting a bit annoying now that this bug is still around, almost a year after it's has been reported, and after it has been given priority. It prevents me to migrate to Magento 2 because it's very confusing for customers.

**Comment by onlinemusketeers** [comment]
@Calypso971  I believe that MyParcel should do better research amongst their users/clients. In order to be able to involve important stakeholders and improve the current extensions/plugins. This bug is not really a bug. It's more like a kind of design flaw.
I am client for many years and I have never been asked about giving input or an evaluation.
Wordpress and Magento or the nr 1 and 2 used e-commerce platforms.. For many years now I haven't offered the "pick up on location" because the extension sucks. So we offer a different transporter for that.

@Myparcel. Please do your research well (usability and ux design) :)

**Comment by RichardPerdaan** [comment]
During the tests I did, I saw not longer the problem. However, when I changed from Magento version (to Magento 2.3.3) it didn't work anymore. I am therefore trying to find out what Magento has changed in this version. So that I can make a solution for this.

We are also working to an adjustment for the functionality regarding the delivery options.
Only this adjustment will no longer come in a new version, this year.

**Comment by RichardPerdaan** [comment]
In version [3.1.2](https://github.com/myparcelnl/magento/releases/tag/3.1.2) I fixed the issue: `Problem with more than one shipping method in checkout.`
 
![screencast2019-11-2815-27-18](https://user-images.githubusercontent.com/11389731/69814513-9f44cc80-11f4-11ea-8207-6c4d4c22f6c0.gif)
