### ISSUE TITLE
radio button not working wel

### ISSUE THREAD

**Issue by rsp-vicus** [myparcelnl/magento#398]
**Describe the bug**
When select another shipment method, the MyParcel shipping keeps selected.
![AFREKENEN](https://user-images.githubusercontent.com/31655295/80459715-13fe6d00-8933-11ea-8897-a76d38a05ba5.png)

**To Reproduce**
1. Go to checkout
2. Click on another shipment

**Expected behavior**
When selected another shipment in this case "Afhalen in de winkel" then MyParcel should NOT be selected, in this case "Thuis of op het werk bezorgd"

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Magento 2.3.3
 - Browser - all
 - MyParcel Plugin version 3.1.3

**Additional context**
When disabled MyParcel, everything works fine

**Comment by Calypso971** [comment]
This is a well known issue that has been reported here several times. They are still not able to fix it properly, and when asked about it, after some discussion they just stop answering simple questions like "when can we expect a fix" or "this should have some priority because it's a bug that's present for quite some time, and promises to fix it were never met". See issues #353, #319 and #228 (january 2019!)

**Comment by RichardPerdaan** [comment]
Dear @rsp-vicus and @Calypso971 ,

It is indeed true that this problem has already been reported to us. We take that problem very seriously. It is true that we have been working on this for a long time. The reason it takes so long is because the part we are going to replace is very complex. 
For example, the myparcel delivery options will not only be made for magento 2, but also Magento 1, WooCommerce, PrestaShop and Opencart. Because it has to work well on multiple platforms, it is very complex to make this work well.

The delivery_options are also a big part of the plugin. And because we are now replacing that, a large part of the architecture has also been adjusted.

We are working on the latest parts for mailbox packages and digital stamps. If these work well and our tests go well, we will test the plugin with the first test customers. If you want to use this, you can always contact us at the following email address: support@myparcel.nl.

And @Calypso971 it is true that you asked when you can expect this version. However, I also said that we cannot say exactly when it will be finished. This is because, we have multiple platforms where the delivery options should work. In addition, this code must be stable before we can use it anywhere.

In addition, many new features have been included into the delivery options. Here's a preview:

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/11389731/80690559-404ef080-8acf-11ea-99c0-f4363f1c05f7.gif)

**Comment by Top-CMS** [comment]
Hi, 

What is the status, is this already BETA of?

We are 2 weeks further and want to use more then one shipping method.

**Comment by Calypso971** [comment]
> What is the status, is this already BETA of?
> 
> We are 2 weeks further and want to use more then one shipping method.

LOL... Some time ago they expected to have a first version in april. We're about one month later now. According what Richard wrote: "And @Calypso971 it is true that you asked when you can expect this version. However, I also said that we cannot say exactly when it will be finished. This is because, we have multiple platforms where the delivery options should work. In addition, this code must be stable before we can use it anywhere." you shouldn't expect it for a number of months at least. Reason: as Richard mentioned, they don't even have a tested version, and then they are controlled testing it in the field (couple of customers). There will be errors coming from that, those have to be solved, and only then they'll release a first version. If it's smart to install that first version... that's up to you. 

I see now that a number of bugs all have been mentioned as "next version". Basically what they are saying: "We have abandoned this plugin, we're coming with a new one." With all bugs that come with such a rewrite and possible changes that customers must make to implement the plugin. Great... but at least after 1,5 or 2 years a annoying bug should be fixed...

**Comment by RichardPerdaan** [comment]
This issue is resolved in version [4.0.0-beta.1] (https://github.com/myparceln/magento/releases/tag/4.0.0-beta.1)
