### ISSUE TITLE
As a client I want the Mageplaza Magento 2 One Step Checkout to be compatible again

### ISSUE THREAD

**Issue by TimBlom** [myparcelnl/magento#548]
**Describe the bug**
Since the update of Magento the MyParcel checkout is not compatible with the Mageplaza One Step Checkout anymore. After selecting a delivery date it is not shown in the Magento admin. When deactivating this checkout and activating the default checkout this options works.

**Versions**
- Magento version 2.3.5-p2
- MyParcel plugin version 4.1.4
- Mageplaza Magento 2 One Step Checkout version 2.6.1

**Expected behavior**
The delivery date should be saved in the order.

**Comment by TimBlom** [comment]
Case 01008644

**Comment by mdubbelman** [comment]
Any update on this issue?

**Comment by RichardPerdaan** [comment]
We did a number of tests with the latest version of the MyParcel plugin and the latest version of the Mageplaza Magento 2 One Step Checkout . The problem seems to be solved with the latest versions.

For now I close the issue. If this problem still occurs, it is always possible to open the issue again.
